inventories = {
    "holdable": {
        1: "sword",
        2: "torch",
        3: "map",
        4: "rope",
        5: "shield",
        6: "bow",
        7: "arrows",
        8: "lantern",
        9: "pickaxe",
        10: "hammer",
        11: "axe",
        12: "shovel",
        13: "bucket",
        14: "fishing rod",
        15: "compass",
        16: "coin",
        17: "gem",
        18: "scroll",
        19: "magic staff",
        20: "orb"
    },
    "wearable": {
        1: "helmet",
        2: "armor",
        3: "boots",
        4: "gloves",
        5: "cloak",
        6: "cap",
        7: "jacket",
        8: "pants",
        9: "belt",
        10: "sandals",
        11: "hard hat",
        12: "vest",
        13: "work boots",
        14: "goggles",
        15: "mask",
        16: "crown",
        17: "cape",
        18: "magic robe",
        19: "magic boots",
        20: "magic gloves"
    }
}